server:
  port: 8002
foo: '{cipher}AQBpR7/5Bqi/4fSCoEatFYCkVebbT/HWFV1Uu1trqESRlGZdbeN8+5N/fZrm6wt/G8JbnFNerEk6Ut1lezA0EvPqJAYsZ4ED8LQgqK2I/TDNyGGcoQg2bckshj/6lzO2GYSivcxS7IAclxFb0tRU204HLs6MJQjuquDUX2GJToO6bQ5XBDmhM1uCSG9kqAyu/yOeW3XqQFeIp+jjHD2mGQ2Qenz0ORiEZ/MuiiYLvpvQJpims6ZSzKTdlR1/dEOGxB9+SMIRas72b3x96t/ASnYaBRVOoaZXNg/ZBIcCdd0Ji5jsVIEjZSsCA23948f7mzJJWPh1y92sPTuoSB6PRpc8r5qaRgGzNRc+CclYCprylpHTsm4lQ0L4z0iQhR7S1nQ='
